const q=s=>document.querySelector(s),input=q('#message'),mic=q('#mic'),status=q('#status'),list=q('#list'),empty=q('#empty'),toast=q('#toast'),login=q('#login'),loginForm=q('#loginForm'),syncState=q('#syncState'),config=window.FAMILY_BOARD_CONFIG;
let items=[],size=Number(localStorage.getItem('family-font'))||18,personName=localStorage.getItem('family-person-name')||'',familyCode=sessionStorage.getItem('family-code')||'',listening=false,recognition,refreshTimer;
function notice(text){toast.textContent=text;toast.classList.add('show');clearTimeout(notice.timer);notice.timer=setTimeout(()=>toast.classList.remove('show'),2400)}
async function rpc(name,body){const response=await fetch(`${config.supabaseUrl}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:config.publishableKey,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok)throw new Error(await response.text());const text=await response.text();return text?JSON.parse(text):null}
function speak(text){if(!('speechSynthesis'in window))return notice('這台裝置不支援語音朗讀');speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang='zh-TW';utterance.rate=.85;speechSynthesis.speak(utterance);notice('正在朗讀留言')}
function render(){list.replaceChildren();empty.hidden=Boolean(items.length);items.forEach(item=>{const li=document.createElement('li');li.className='card';const content=document.createElement('p');content.textContent=item.body;const meta=document.createElement('div');meta.className='meta';const info=document.createElement('span');const time=new Intl.DateTimeFormat('zh-TW',{dateStyle:'long',timeStyle:'short'}).format(new Date(item.created_at));info.textContent=`${item.author}・${time}`;const actions=document.createElement('span'),read=document.createElement('button'),remove=document.createElement('button');read.textContent='🔊 朗讀';read.onclick=()=>speak(`${item.author}說：${item.body}`);remove.textContent='刪除';remove.className='delete';remove.onclick=async()=>{if(!confirm('確定要刪除這一筆留言嗎？'))return;try{await rpc('family_delete_message',{p_family_code:familyCode,p_message_id:item.id});await loadMessages();notice('留言已刪除')}catch{notice('刪除失敗，請檢查網路')}};actions.append(read,remove);meta.append(info,actions);li.append(content,meta);list.append(li)})}
async function loadMessages(showError=false){if(!familyCode)return;syncState.textContent='同步中…';try{items=await rpc('family_list_messages',{p_family_code:familyCode});render();syncState.textContent='已同步'}catch{syncState.textContent='連線失敗';if(showError)throw new Error('login failed')}}
loginForm.addEventListener('submit',async event=>{event.preventDefault();personName=q('#personName').value.trim();familyCode=q('#familyCode').value;q('#loginStatus').textContent='正在確認家庭密碼…';try{const valid=await rpc('family_check_code',{p_family_code:familyCode});if(!valid)throw new Error('invalid code');await loadMessages(true);localStorage.setItem('family-person-name',personName);sessionStorage.setItem('family-code',familyCode);login.hidden=true;q('#familyCode').value='';q('#loginStatus').textContent='';clearInterval(refreshTimer);refreshTimer=setInterval(loadMessages,10000)}catch{familyCode='';q('#loginStatus').textContent='家庭密碼不正確，或網路暫時無法連線'}});
q('#save').onclick=async()=>{const text=input.value.trim();if(!text){notice('請先說話或寫下留言');return input.focus()}q('#save').disabled=true;try{await rpc('family_add_message',{p_family_code:familyCode,p_author:personName,p_body:text});input.value='';await loadMessages();notice('全家都看得到這則留言了');list.scrollIntoView({behavior:'smooth',block:'center'})}catch{notice('儲存失敗，請檢查網路')}finally{q('#save').disabled=false}};
q('#logout').onclick=()=>{sessionStorage.removeItem('family-code');familyCode='';clearInterval(refreshTimer);login.hidden=false;q('#personName').value=personName;q('#familyCode').focus()};
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(SR){recognition=new SR;recognition.lang='zh-TW';recognition.interimResults=true;recognition.continuous=true;let before='';recognition.onstart=()=>{listening=true;before=input.value.trim();mic.classList.add('listening');mic.setAttribute('aria-pressed','true');q('#mic span').textContent='正在聽，按一下結束';status.textContent='請開始說話，我正在聽…'};recognition.onresult=event=>{let text='';for(let i=event.resultIndex;i<event.results.length;i++)text+=event.results[i][0].transcript;input.value=[before,text].filter(Boolean).join(before?'，':'')};recognition.onend=()=>{listening=false;mic.classList.remove('listening');mic.setAttribute('aria-pressed','false');q('#mic span').textContent='按一下，開始說話';status.textContent=input.value?'語音輸入完成，可以儲存留言了':'準備好了，請按麥克風開始說話'};recognition.onerror=event=>status.textContent=({'not-allowed':'請允許網站使用麥克風','no-speech':'沒有聽到聲音，請再試一次',network:'語音服務暫時無法連線'}[event.error]||'沒有聽清楚，請再試一次');mic.onclick=()=>listening?recognition.stop():recognition.start()}else{mic.disabled=true;q('#mic span').textContent='瀏覽器不支援語音輸入';status.textContent='請改用手機鍵盤的麥克風按鈕說話'}
function applyFont(){document.documentElement.style.setProperty('--size',`${size}px`);localStorage.setItem('family-font',size)}q('#larger').onclick=()=>{size=Math.min(24,size+2);applyFont();notice(`字體大小 ${size}`)};q('#smaller').onclick=()=>{size=Math.max(16,size-2);applyFont();notice(`字體大小 ${size}`)};const contrast=q('#contrast'),savedContrast=localStorage.getItem('family-contrast')==='true';document.body.classList.toggle('high',savedContrast);contrast.setAttribute('aria-pressed',String(savedContrast));contrast.onclick=()=>{const on=document.body.classList.toggle('high');contrast.setAttribute('aria-pressed',String(on));localStorage.setItem('family-contrast',String(on));notice(on?'已開啟高對比':'已關閉高對比')};
q('#personName').value=personName;applyFont();if(familyCode&&personName){login.hidden=true;loadMessages().then(()=>refreshTimer=setInterval(loadMessages,10000))}if('serviceWorker'in navigator&&location.protocol==='https:')window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
